export const theme = {
  colors: {
    typography: {
      text: "#A2A4A6",
      blue: "#3887FE",
      title: "#06152b",
      subtitle: "#06152b",
      body: "#acacac",
      placeholder: "#7a7a7a",
      small: "#809fb8",
      mediumGray: "#877d8e",
      gray: "#B2B2B2",
      lightGray: "#C4CCD1",
      darkGray: "#00233B",
      blueGray: "#D9E1E7",
      white: "#ffffff",
    },

    actions: {
      success: "#28B369",
      successDark: "#136338",
      info: "#1B81D2",
      infoDark: "#0e426c",
      warning: "#EFAE26",
      error: "#ff1212",
      errorDark: "#8b0d0d",
      disabled: "#ededed",
    },

    components: {
      active: "#7941EC",
      activeBg: "#3e3e45",
      header: "#2456a2",
      menu: "#2f2f34",
      hover: "#7941EC",
      darkPurple: "#50289f",
      backgroundGray: "#191c1e",
      background: "#ffffff",
      border: "#C6C6C6",
      placeholder: "#AFAFAF",
      table: "#38383d",
      mediumGray: "#47464d",
      form: "#535259",
    },

    input: {
      bg: "#50289f",
      text: "#ffffff",
      border: "#2456a2",
      hoverBg: "#7941EC",
      hoverBorder: "#4183e5",
      // hoverText: "transparent",
      disabledBg: "#2f2f34",
      disabledBorder: "#3e3e45",
      disabledText: "#3e3e45",
    },

    button: {
      primary: {
        bg: "#582bb1",
        text: "#ffffff",
        // border: "transparent",
        hoverBg: "#7941EC",
        // hoverBorder: "transparent",
        // hoverText: "transparent",
        disabledBg: "#58575d",
        // disabledBorder: "transparent",
        disabledText: "#8d8d8d",
      },

      secondary: {
        bg: "transparent",
        text: "#ff1212",
        border: "#ff1212",
        hoverBg: "transparent",
        hoverBorder: "#ff6363",
        hoverText: "#ff6363",
        disabledBg: "#414141",
        disabledBorder: "#b8b8b8",
        disabledText: "#b8b8b8",
      },

      tertiary: {
        bg: "#ffffff",
        text: "#A2A4A6",
        border: "#A2A4A6",
        hoverBg: "#ffffff",
        hoverBorder: "#169A55",
        hoverText: "#169A55",
        disabledBg: "#ffffff",
        disabledBorder: "#e6e6e6",
        disabledText: "#e6e6e6",
      },
    },
  },
};
